### ISSUE TITLE
Journal Articles on Biblical Literalism

### ISSUE THREAD

**Issue by SSingh132** [justindoran/doran-sra-summer2022#1]
Create a bibliography about information on Biblical Literalism.

**Comment by SSingh132** [comment]
[BiblicalLiteralismBib.txt](https://github.com/justindoran/doran-sra-summer2022/files/8929227/BiblicalLiteralismBib.txt)

**Comment by SSingh132** [comment]
**Juzwik, Mary M. “American Evangelical Biblicism as Literate Practice: A Critical Review.” Reading Research Quarterly 49, no. 3 (2014): 335–49.**
- Biblical Literalism is essentially the practice of Christians taking the Bible very literally, and believing in its applicability to the world we live in and how we should go about our daily lives. This is thought to be a common practice for evangelicals. And while it is in a way, it's more that many evangelicals have parts of the bible that they take very literally and claim as the God-given truth, while other parts are not as much. Still, they hold the Bible as extremely authoritative, but still think it is open to constant interpretation, as that is kind of how the Pentecostal movement started in the first place and continues to evolve. 
- Innerancy is the idea that the Bible is without error, which is also common among evangelicals.
- Evangelicism is diverse, and a lot of different subgroups are part of the larger categorization of "evangelical."
- Specifically cites the Book of Acts as something that became a new model for people to live their lives off of. Different Biblical literalists will do different things because of how they perceive its "literal" meaning. And for many of the born-again movement, the ideas of being saved by the Holy Spirit became what they pinpointed on. Thus, the Bible is imbued with a lot of meaning for them, and it impacts how they act in their daily lives. 
- Much of the evangelical interpretation of the Bible comes through a pastor or study group. The interpretation and discourse within the community around the Bible then becomes more important to the members of the movement than their actual reading of the Bible. This is why the belief of homosexuality being a sin is so prominent within the movement despite it not being that prominent in the actual Bible. It is an example of how evangelical leaders focused on something and emphasized it in their Biblicism, and then spread that across the movement.

Boyd, Heather Hartwig. “Christianity and the Environment in the American Public.” Journal for the Scientific Study of Religion 38, no. 1 (1999): 36–44. https://doi.org/10.2307/1387582.
- "A more 'gracious' image of God (mother, spouse, lover, friend, as opposed to father, master, judge, and king) was positively correlated with support for increased spending on the environment." Thus, different interpretations of the imagery of the Bible heavily impact people's views on environmentalism. This could point to our understanding of strong Biblical adherence not being a bad thing, but rather the specific interpretations of the pastors and leaders of the movement described in Juzwik's writing is what is shaping the imagery of the entire movement, and thus, shaping a completely different outlook on the world. If everyone could adhere to the Bible but with their own sensibilities and liberties in interpreting its meaning, we would have a vastly different movement probably. 

Bartkowski, John. “Beyond Biblical Literalism and Inerrancy: Conservative Protestants and the Hermeneutic Interpretation of Scripture.” Sociology of Religion 57, no. 3 (1996): 259–72. https://doi.org/10.2307/3712156.
- This echoes Juzwik's article by saying many who self-identify as "evangelical" don't take the Bible literally in every sense but do still consider it "authoritative." This gives the movement flexibility in the evolution of their beliefs while still being staunchly committed to and unwavering in their faith in them. It's not cut and dry like that though, there is such a diversity of how people look at the Bible. Ultimately though, for evangelicals it is mostly considered a highly authoritative text.
- When it comes to biblical interpretation, "what the text means now matters more than what the author meant when he [or she] wrote it." Furthermore, what is means now to people is highly influenced by the biases and prejudices they have while interpreting the Bible. This is why the promotion of patriarchal spousal relations are so prominent within the community, despite it not being a premier feature of the Bible. However, because it exists there, and people with gendered prejudices are reading it, their own biases make that feature compound upon itself and turn it into a larger, more detailed stance on gender relations than the Bible actually takes, sometimes just adding their own thoughts on the subject. So while people who have more conservative stances on political issues may seem to be "biblical literalists," most are not, there can't really be a literal interpretation of the Bible, because what we perceive as its literal meaning still has a lot to do with our own prejudices and biases and assumptions. Thus, two biblical literalists can have different interpretations of the same passage.

Franzen, Aaron B., and Jenna Griebel. “Understanding a Cultural Identity: The Confluence of Education, Politics, and Religion within the American Concept of Biblical Literalism.” Sociology of Religion 74, no. 4 (2013): 521–43.
- Biblical Literalists has become more of a term to use to define a group of people whose interpretation of the Bible more liberal people don't like rather than a group of strict adherents to the word of the Bible. It's an identity marker.

Greeley, Andrew. “Religion and Attitudes toward the Environment.” Journal for the Scientific Study of Religion 32, no. 1 (1993): 19–28. https://doi.org/10.2307/1386911.
Biblical literalist interpretation of the Bible has led people to believe they should "exercise 'dominion' over the earth." This has long been an explanation for why Christians are not pro-environment. However, Greeley seems to argue that the political views of many fundamentalists can be separate from their religious beliefs, and the reason so many Christians aren't pro-environment is just because many Christians are conservative.

**Comment by justindoran** [comment]
Solid work @SSingh132, annotations should go in the file itself. Once you put them in there, we can close this issue.
