### ISSUE TITLE
Create Snake Handling Bibliography 

### ISSUE THREAD

**Issue by Lkanady** [justindoran/doran-sra-summer2022#2]

**Comment by justindoran** [comment]
Since you created it, you can close this issue, @Lkanady

**Comment by Lkanady** [comment]
Learned some interesting things about Appalachian culture from this research as well as a better understanding of how/why snake handling blossomed in this region.

**Comment by Lkanady** [comment]
/Users/lilykanady/doran-sra-summer2022/Snake Handling Bibliography.md

**Comment by Lkanady** [comment]
/Users/lilykanady/doran-sra-summer2022/Snake Handling Bibliography.md
