### ISSUE TITLE
Compose a cursory list of anything published since 2015 on Pentecostalism and Capitalism

### ISSUE THREAD

**Issue by SSingh132** [justindoran/doran-sra-summer2022#23]

**Comment by Lkanady** [comment]
/Users/lilykanady/doran-sra-summer2022/Church History Bibliography.md

**Comment by SSingh132** [comment]
[New Pentecostalism Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/8993504/New.Pentecostalism.Bibliography.md)

**Comment by Lkanady** [comment]
/Users/lilykanady/doran-sra-summer2022/Politics and Religion Bibliography.md

**Comment by Lkanady** [comment]
/Users/lilykanady/doran-sra-summer2022/Politics and Religion Bibliography.md

**Comment by Lkanady** [comment]
[Church History Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/8993516/Church.History.Bibliography.md)

**Comment by Lkanady** [comment]
[Politics and Religion Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/8993518/Politics.and.Religion.Bibliography.md)

**Comment by Lkanady** [comment]
[The Journal of Religion Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/8993519/The.Journal.of.Religion.Bibliography.md)

**Comment by Lkanady** [comment]
[JAAR Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/8993527/JAAR.Bibliography.md)

**Comment by SSingh132** [comment]
[Nova Religio Sources.md](https://github.com/justindoran/doran-sra-summer2022/files/8993559/Nova.Religio.Sources.md)
