### ISSUE TITLE
Have Doran check the bibliography and choose a high value source

### ISSUE THREAD

**Issue by SSingh132** [justindoran/doran-sra-summer2022#24]

**Comment by justindoran** [comment]
@SSingh132 and @Lkanady we should read deeply into one of these high value sources each and discuss what their arguments are, here are the options: 

The two bests sources you found in /New Pentecostalism Bibliography.md are Brenneman and Coleman/Chattoo, I recommend we read both of them more deeply. I am a little uncertain (memory is failing me) if we meant to dig through this bibliography for the high value source, or if it was /New Experiences in Capitalism Bib.md. If it was the second one then the two sources we should read are Meyer and Yong/Attanasi. 

As an aside, we need to get in the habit of adding descriptions to issues when the task is fresh in our mind. It never hurts to over-explain to ourselves what we are doing.
