### ISSUE TITLE
Read a high value source from the Pentecostalism bibliography carefully

### ISSUE THREAD

**Issue by SSingh132** [justindoran/doran-sra-summer2022#25]
After Dr. Doran reviews our Bibliography on the latest research on Pentecostalism and Capitalism, he will select a high-value source from it and we need to read it and snowball other sources from it.

- [x] Read High Value Source

**Comment by Lkanady** [comment]
I am reading "The Applause of Heaven: Max Lucado and the Cutesy in American Evangelicalism" by Brenneman
