### ISSUE TITLE
Create bibliography on Relationship Between Evangelicals and Jews

### ISSUE THREAD

**Issue by SSingh132** [justindoran/doran-sra-summer2022#3]
A bibliography that contains sources on the relationships between Christians and Jews, both focusing on their anti-Semitism, and their pro-Israel stances.

**Comment by SSingh132** [comment]
[Evangelical-Jewish.txt](https://github.com/justindoran/doran-sra-summer2022/files/8931469/Evangelical-Jewish.txt)

**Comment by justindoran** [comment]
Awesome, thanks for taking the initiative, @SSingh132 , make sure to name the issue after the action you'll be taking, so we know explicitly when it's done and can be closed.
