### ISSUE TITLE
Research James Bopp Jr.

### ISSUE THREAD

**Issue by justindoran** [justindoran/doran-sra-summer2022#37]
The lawyer I was thinking of was James Bopp Jr. We should find out whether there is more rigorous research out there about him. Here is a news report as a starting point:

https://www.youtube.com/watch?v=a4B3VbaqjlA

**Comment by SSingh132** [comment]
[James Bopp Jr. Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/9013273/James.Bopp.Jr.Bibliography.md)
