### ISSUE TITLE
Exploratory Research into QANON's recent posts

### ISSUE THREAD

**Issue by Lkanady** [justindoran/doran-sra-summer2022#48]
Ron Watkins is suspect of being Q, but is he posting this time around or is he in cahoots with someone else who is posting? Posts as a response to recent insurrection testimonies. 

- [x] Research testimony of Mark Meadow's aid who was present at the insurrection. 
- [x] Turn to news coverage to learn more about QANON's recent activity. 
- [x] Look through 8kun to see how people are reacting to Q's return

**Comment by SSingh132** [comment]
We've done all of these, but I want to do a little bit more with it so that's why I haven't closed it just yet.

**Comment by SSingh132** [comment]
[QAnon Bibliography.md](https://github.com/justindoran/doran-sra-summer2022/files/9024341/QAnon.Bibliography.md)
